### ISSUE TITLE
dagger-guice-rf-activities archetypes not working

### ISSUE THREAD

**Issue by kaisumli** [tbroyer/gwt-maven-archetypes#51]
I am trying to create a new project using the dagger-guice-rf-activities archetypes.
I run this command:
mvn archetype:generate \
   -DarchetypeGroupId=net.ltgt.gwt.archetypes \
   -DarchetypeVersion=LATEST \
   -DarchetypeArtifactId=dagger-guice-rf-activities

Once it finishes setting up the project, I cd into the directory and run:
mvn gwt:codeserver -pl *-client -am
which starts up the code server.
Then I start another terminal and runs mvn tomcat7:run -pl *-server -am -Denv=dev
Now it gives me this error

[INFO] ------------------------------------------------------------------------
[INFO] Building report-server 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> tomcat7-maven-plugin:2.2:run (default-cli) > process-classes @ report-server >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ report-server ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/tor/Documents/reporting/report/report-server/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ report-server ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (requestfactory-validation-tool) @ report-server ---
[INFO] 
[INFO] <<< tomcat7-maven-plugin:2.2:run (default-cli) < process-classes @ report-server <<<
[INFO] 
[INFO] 
[INFO] --- tomcat7-maven-plugin:2.2:run (default-cli) @ report-server ---
[INFO] Running war on http://localhost:8080/
[INFO] Using existing Tomcat server configuration at /Users/tor/Documents/reporting/report/report-server/target/tomcat
[INFO] use tomcat-users.xml from /Users/tor/Documents/reporting/report/report-server/src/main/tomcatconf/tomcat-users.xml
[INFO] create webapp with contextPath: 
Dec 06, 2017 3:54:29 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Dec 06, 2017 3:54:29 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Dec 06, 2017 3:54:29 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47
Dec 06, 2017 3:54:30 PM com.google.web.bindery.requestfactory.server.ReflectiveServiceLayer <clinit>
INFO: Unable to initialize a JSR 303 Bean Validator
javax.validation.ValidationException: Unable to find a default provider
	at javax.validation.Validation$GenericBootstrapImpl.configure(Validation.java:264)
	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:111)
	at com.google.web.bindery.requestfactory.server.ReflectiveServiceLayer.<clinit>(ReflectiveServiceLayer.java:60)
	at com.google.web.bindery.requestfactory.server.ServiceLayer.create(ServiceLayer.java:75)
	at com.google.web.bindery.requestfactory.server.RequestFactoryServlet.<init>(RequestFactoryServlet.java:105)
	at al.tor.report.GuiceRequestFactoryServlet.<init>(GuiceRequestFactoryServlet.java:14)
	at al.tor.report.GuiceRequestFactoryServlet$$FastClassByGuice$$cb96cad5.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:268)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:194)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1019)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1085)
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1015)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1050)
	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:111)
	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:103)
	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:226)
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:281)
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:262)
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:107)
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4775)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5452)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Dec 06, 2017 3:54:30 PM org.apache.coyote.AbstractProtocol start

Is it missing some dependency? Any suggestions?

Thanks!
Kai

**Comment by tbroyer** [comment]
See https://github.com/gwtproject/gwt/issues/5783#issuecomment-110827753
